
export default {
    name: 'Usuario',
    data () {
      return {
        model:{
            idusuario:'1',
            nombres:'Samael',
            apellidos:'Veritas',
            password:'',
            docnum:'12345678',
            doctipo:'DNI',
            correo:'sveritas@salud.com',
            telefono:'987654321',
            direccion:'Psje. 123',
            procedencia:'Peruano',
            rol:"Administrador",
            numcolegiatura:"123456",
            especialidad:["Cardiología"],
        },
        rol:{
            idrol:'',
            descripcion:'',
        },

        tipo_doc: ['DNI', 'Carnet de Extranjería', 'Pasaporte'],
        roles: [
          {nombre:'Administrador',descripcion:'Acceso completo al sistema'},
          {nombre:'Médico',descripcion:'Acceso parcial al sistema'},
          {nombre:'Enfermero',descripcion:'Acceso parcial al sistema'}
        ],
        especialidades:[
          "Alergología",
          "Cardiología",
          "Cirugía de Cabeza y Cuello",
          "Cirugía de Torax y Cardiovascular",
          "Cirugía General y Laparoscópica",
          "Cirugía Oncológica",
          "Cirugía Pediátrica",
          "Dermatología",
          "Ecografía",
          "Endocrinología",
          "Gastroenterología",
          "Geriatría",
          "Ginecología Oncológica",
          "Ginecología y Obstetricia",
          "Hematología",
          "Mastología",
          "Medicina Física y Rehabilitación",
          "Medicina General",
          "Medicina Interna",
          "Nefrología",
          "Neumología",
          "Neurocirugía",
          "Neurología",
          "Nutrición",
          "Odontología",
          "Oftalmología",
          "Otorrinolaringología",
          "Pediatría",
          "Psicología",
          "Radiología",
          "Reumatologia",
          "Salud Mental",
          "Traumatologia y Ortopedia",
          "Urología",
        ]
      }
    },
  }
